# Generated by Django 4.0.1 on 2022-02-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
